#!/usr/bin/env bash
# Displays information about several subdomains connected to domain
# Usage: ./0-world_wide_web <domain> <subdomain>

# Function retrieves and displays info about subdomain
domain_info() {
	# DNS lookup for subdomain under specified domain
	line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	# Extract relevant info and print it
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to "$3}'
}

# Check command-line argument
if [ "$#" === 1]
then
    # If only 1 arg, call subdomain_info function with subdom names
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" === 2 ]
then
    # If 2 args call domain_info function along subdomain name
    domain_info "$1" "$2"
fi
