#!/usr/bin/env bash
# Usage: domain_info <domain> <subdomain>

# Function that retrieves and displays info about subdomain
domain_info() {
    # DNS Lookup for subdomain of a specific domain
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    # Extract info and print output
    echo "$1 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to a " $3}'
}

# Check number of command-line arguments
if [ "$#" == 1 ]
then
    # If only 1 argument call domain_info with prdefined subdomain name
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
    # if two arguments, call domain_info with provided subdomain name
    domain_info "$1" "$2"
fi
