#!/usr/bin/env bash
# A bash script that transfers a file to my remote directory using scp
# scp stands for Secure Copy Protocol

if [ "$#" -ne 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

scp -o StrictHostCheck=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:/home/ubuntu/"
