#!/usr/bin/env bash
# Bash script configuring server to redirect redirect_me to another page.
# The redirection must be a “301 Moved Permanently”
redirection_string="server_name _:\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent"
sudo sed -i "s/server_name _:/$redirection_string/" /etc/nginx/sites-enabled
