#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string


# Updating and installing Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
redirect_string="server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s|server_name _;|$redirect_string|" /etc/nginx/sites-available/default

# Create a custom 404 page
echo -e "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use custom 404 page
error_404="server_name _;\n\terror_page 404 /404.html;\n\tlocation = /404.html{\n\tinternal;\n\t}"
sudo sed -i "s|server_name _;|$error_404|" /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart