#!/usr/bin/env bash
# A bash script that configures a brand new Ubuntu machine to the requirements

# Update package index/extensions
sudo apt-get -y update

# Install nginx server
sudo apt-get -y install nginx

# start server
sudo service nginx start

# Granting directories and files necessary permissions
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/

# Writing content to a simple html page
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Get the hostname
hostname=$(hostname)

# Add add_header directive under server block
header_string="server_name _;\n\tadd_header X-Served-By $hostname;"
sudo sed -i "s|server_name _;|$header_string|" /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart nginx server
sudo service nginx restart
