#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# Update package list
sudo apt-get update

# Instsll HAProxy
sudo apt -y install haproxy

# Backup default configuration settings and configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
  log /dev/log local0
  log /dev/log local1 notice
  chroot /var/lib/haproxy
  stats socket run/haproxy/admin.sock mode 660 level admin
  stats timeout 30s
  user haproxy
  group haproxy

defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000

frontend http_front
  bind *:80
  default_backend http_back

backend http_back
  balance roundrobin
  server 446229-web-01 34.204.101.147:80 check
  server 446229-web-02 3.85.33.239:80 check
EOT

# Restart HAProxy to apply changes
sudo service restart haproxy

# Enable HAProxy to start on boot
sudo service enable haproxy

# Verify HAProxy status
sudo service restart haproxy
