#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

# Update package list
sudo apt-get update

# Instsll HAProxy
sudo apt install -y haproxy

# enable mangement via init script
echo "ENABLED=1" >> /etc/default/haproxy

# Backup default configuration settings and configure HAProxy
mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
touch /etc/haproxy/haproxy.cfg

printf %s "global
  log 127.0.0.1 local0 notice
  maxconn 2000
  user haproxy
  group haproxy

defaults
  log global
  mode http
  option httplog
  option dontlognull
  retries 3
  option redispatch
  timeout connect 5000
  timeout client 50000
  timeout server 50000
  errorfile 400 /etc/haproxy/errors/400.http
  errorfile 403 /etc/haproxy/errors/403.http
  errorfile 408 /etc/haproxy/errors/408.http
  errorfile 500 /etc/haproxy/errors/500.http
  errorfile 502 /etc/haproxy/errors/502.http
  errorfile 503 /etc/haproxy/errors/503.http
  errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
  timeout client 50000
  bind 0:80
  default_backend servers

backend servers
  timeout connect 5000
  timeout server 50000
  balance roundrobin
  server 446229-web-01 34.204.101.147:80 check
  server 446229-web-02 3.85.33.239:80 check

" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply changes
sudo service haproxy restart
