#!/usr/bin/env bash
# A bash script that install MySQL version 5.7
sudo wget -O mysql57 https://raw.githubusercontent.com/nuuxcode/alx-system_engineering-devops/master/scripts/mysql57 && sudo chmod 755 mysql57 && ./mysql57
