#!/usr/bin/env bash
# A bash script setting up source/primary replication

# Allow incoming traffic from replica server
sudo ufw allow 54.90.29.151 to port on 3306

# Unique identifier used internally to distinguish servers during replication
sed -i '/\[mysql\]/a server_id	= 1' /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i '/\[mysql\]/log_bin	= /var/log/mysql/mysql-bin.log' /etc/mysql/mysql.conf.d/mysqld.cnf
sed -i '/\[mysql\]/binlog_do_db	= tyrell_corp' /etc/mysql/mysql.conf.d/mysqld.cnf

sudo service service mysql restart
