#!/usr/bin/env bash
# A bash script generating a MySQL dumpfile and a compressed archive(backup)
if [ $# -ne 1 ]
then
	echo "Usage: $0 password"
	exit 1
fi

password=$1
timestamp=$(date "+%d-%m-%Y")
backup_dir="."
backup_file="backup.sql"
compressed_backup_file="${timestamp}.tar.gz"

# Dump all databases to a SQL file
sudo mysqldump -uroot -p"${password}" --all-databases > "${backup_dir}/${backup_file}"

# Compress the SQL file
tar -czf "${backup_dir}/${compressed_backup_file}" -C "${backup_dir}" "${backup_file}"
