#!/usr/bin/env bash
# A bash script that pings an IP address as argument
#+ It should accept a string as argument
#+ displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#+ Otherwise, pings IP 5 times
if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed"
else
	ping -c 5 "$1"
fi
