#!/usr/bin/env bash
# A bash script that checks if server is listening on port 8-

# Remove default configuration file incase something changed
rm /etc/nginx/sites-enabled/default

# Configure nginx to listen on port 80 for all IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx service
service nginx restart
