#!/usr/bin/env bash
# A bash script that
#+ Creates the file /var/run/myscript.pid containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command when receiving a SIGTERM signal
#+ Displays Y U no love me?! when receiving a SIGINT signal
#+ Deletes the file /var/run/myscript.pid and terminates itself
#+ when receiving a SIGQUIT or SIGTERM signa

echo "$$" > /var/run/myscript.pid

del_file(){
	rm /var/run/myscript.pid
	exit
}
while true;
do
	echo "To infinity and beyond"
	trap 'echo "I hate the kill command" && del_file' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'del_file' SIGQUIT
done
