#!/usr/bin/env bash
# A bash script that
#+ Creates the file /var/run/myscript.pid containing its PID
#+ Displays To infinity and beyond indefinitely
#+ Displays I hate the kill command when receiving a SIGTERM signal
#+ Displays Y U no love me?! when receiving a SIGINT signal
#+ Deletes the file /var/run/myscript.pid and terminates itself
#+ when receiving a SIGQUIT or SIGTERM signa

file_pid="/var/run/myscript.pid"
echo $$ > "$file_pid"

trap 'echo "I hate the kill command"; exit' SIGTERM

trap 'echo "Y U no love me?!"; exit' SIGINT

trap "del_file" SIGQUIT

del_file(){
	echo "clean up and exit"
	rm -f "$file-pid"
	exit
}
while true;do
	echo "To infinity and beyond"
done
