#!/usr/bin/env bash
# A Bash script that displays 'To infinity and beyond indefinitely
#+ sleeps between two iterations
#+ displays 'I am invicible" on receiving SIGTERM

terminate(){
	echo "I am invicible!!!"
}

trap terminate SIGTERM

while true;
do
	echo "To infinity and beyond"
	sleep 2
done

