#!/usr/bin/env bash
# A script that displays the time for 12 hours and 59 minutes:
#+ display hours from 0 to 12
#+ display minutes from 1 to 59
n=0
while [ $n -lt 13 ];
do
	echo "Hour: $n"
	m=1
	while [ "$m" -lt 60 ];
	do
		echo "$m"
		((m++))
	done
	((n++))
done
