#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install Uncomplicated Firewall
sudo apt install ufw

# Display UFW status
sudo ufw status

# Set default configuration
sudo ufw deny incomming

# Allow necessary ports (SSH, HTTPS, HTTP)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable firewall
sudo ufw enable
