#!/usr/bin/env bash

# Update package lists
sudo apt-get -y update

# Install Uncomplicated Firewall
sudo apt -y install ufw

# Display UFW status
sudo ufw status

# Set default configuration
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow necessary ports (SSH, HTTPS/SSL, HTTP)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable firewall
sudo ufw enable
