#!/usr/bin/env bash
# A bash script that configures an Ubuntu server as follows
#+ localhost resolves to 127.0.0.1
#+ facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
echo "localhost		127.0.0.2" > ~/hosts.new
echo "facebook.com	8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
