#!/usr/bin/env bash
# A bash script that run user(Nginx) as user(Nginx)

# In-place file text edit to update user as nginx
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

# nginx listens on all active IPs on port 8080
sed -i '/^http {/a \	listen 8080' /etc/nginx/nginx.conf

service nginx restart
