#!/usr/bin/env bash
# A bash script using SSH client side config to enable connection without password
Hostname 446229-web-01
  HostName 34.204.101.147
  User 'ubuntu'
  IdentityFile '~/.ssh/school'

